[2024-06-21T21:30:16.797+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-06-21T20:51:07.332473+00:00 [queued]>
[2024-06-21T21:30:16.804+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-06-21T20:51:07.332473+00:00 [queued]>
[2024-06-21T21:30:16.804+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-06-21T21:30:16.817+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2024-06-21 20:51:07.332473+00:00
[2024-06-21T21:30:16.824+0000] {standard_task_runner.py:57} INFO - Started process 86569 to run task
[2024-06-21T21:30:16.828+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2024-06-21T20:51:07.332473+00:00', '--job-id', '2000', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpc4hzak81']
[2024-06-21T21:30:16.830+0000] {standard_task_runner.py:85} INFO - Job 2000: Subtask kafka_data_stream
[2024-06-21T21:30:16.928+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-06-21T20:51:07.332473+00:00 [running]> on host 2ad9230613d5
[2024-06-21T21:30:17.002+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T20:51:07.332473+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-21T20:51:07.332473+00:00'
[2024-06-21T21:30:17.027+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-21T21:30:17.028+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:9092 (0)
[2024-06-21T21:30:17.028+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-06-21T21:30:17.043+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-21T21:30:17.044+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:9092 (0)
[2024-06-21T21:30:17.045+0000] {kafka_stream_data.py:127} INFO - We assume that we are running locally, so we use localhost instead of kafka and the external port 9094
[2024-06-21T21:30:17.048+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: connecting to localhost:9094 [('127.0.0.1', 9094) IPv4]
[2024-06-21T21:30:17.049+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-06-21T21:30:17.050+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]> returned error 111. Disconnecting.
[2024-06-21T21:30:17.050+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-21T21:30:17.097+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: connecting to localhost:9094 [('127.0.0.1', 9094) IPv4]
[2024-06-21T21:30:17.098+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]> returned error 111. Disconnecting.
[2024-06-21T21:30:17.098+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-21T21:30:17.147+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: connecting to localhost:9094 [('::1', 9094, 0, 0) IPv6]
[2024-06-21T21:30:17.148+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]> returned error 99. Disconnecting.
[2024-06-21T21:30:17.149+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: Closing connection. KafkaConnectionError: 99 EADDRNOTAVAIL
[2024-06-21T21:30:17.151+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/src/kafka_client/kafka_stream_data.py", line 125, in create_kafka_producer
    producer = KafkaProducer(bootstrap_servers=["kafka:9092"])
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/kafka_client/kafka_stream_data.py", line 148, in stream
    producer = create_kafka_producer()
  File "/opt/airflow/dags/src/kafka_client/kafka_stream_data.py", line 131, in create_kafka_producer
    producer = KafkaProducer(bootstrap_servers=["localhost:9094"])
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-06-21T21:30:17.169+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20240621T205107, start_date=20240621T213016, end_date=20240621T213017
[2024-06-21T21:30:17.179+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2000 for task kafka_data_stream (NoBrokersAvailable; 86569)
[2024-06-21T21:30:17.218+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
